obstacle_range: 4.0
raytrace_range: 5.0
#footfrint: [[3.0, 3.0], [3.0, -3.0], [-3.0, -3.0], [-3.0, 3.0]]
robot_radius: 2.0
inflation_radius: 2.0
max_obstacle_height: 1.6
min_obstacle_height: 1.3
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
#scan: {sensor_frame: velodyne_dipan_scan_joint, data_type: Pointcloud2, topic: /velodyne_points, marking: true, clearing: true, expected_update_rate: 0}
