arm:
  arm_dzy_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - base_25a
      - a25_arm1
      - arm1_20a
      - a20_arm2
      - arm2_14a
      - a14_adapter
      - pin_tou

    constraints:
        goal_time: 1.6
        stopped_velocity_tolerance: 0.1

    stop_trajectory_duration: 0.05
    state_publish_rate:  25
    action_monitor_rate: 10
