# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_dzy
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_25a
    - a25_arm1
    - arm1_20a
    - a20_arm2
    - arm2_14a
    - a14_adapter
    - pin_tou
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
controller_manager_ns: controller_manager
controller_list:
  - name: arm/arm_dzy_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_25a
      - a25_arm1
      - arm1_20a
      - a20_arm2
      - arm2_14a
      - a14_adapter
      - pin_tou
